### ISSUE TITLE
SSL certificate doesn't list www.loglist.net

### ISSUE THREAD

**Issue by Minoru** [codingteam/devops#30]
https://codingteam.org.ru/resources links to https://www.loglist.net/, but TLS connection to the latter fails because the SSL certificate is only valid for codingteam.org.ru, loglist.net and tales.codingteam.org.ru.

**Comment by ForNeVeR** [comment]
I'd really like to re-register the certificate with `www.loglist.net` included, but currently we're hitting some internal letsencrypt rate-limit:

```
{
  "type": "urn:acme:error:rateLimited",
  "detail": "Error creating new cert :: too many certificates already issued for: org.ru",
  "status": 429
}
```

It's probably linked with
1) the fact that I have already regenerated the certificate last Sunday
2) [some strange issues with `org.ru` on letsencrypt](https://community.letsencrypt.org/t/publicsuffix-list-should-be-replaced-with-dedicated-solution/35549)

For now, as a temporary (but anyways good) solution I'll just go and change the public link to `loglist.net` instead of `www.loglist.net`. We also encourage users to not use that obsolete `www` prefix anymore.

I'll try to register the domains in the meantime, and will monitor the corresponding [publicsuffix list pull-request](https://github.com/publicsuffix/list/pull/412) closely.

Generally, it seems that we're in trouble here.

**Comment by ForNeVeR** [comment]
It has been fixed on the site, see https://github.com/codingteam/codingteam.org.ru/pull/66

Currently I'm thinking about dropping that `www` prefix at all. Any thoughts?

We have explicit redirects from `*.loglist.net` to just `loglist.net` in our nginx config: https://github.com/codingteam/devops/blob/ccec1831bced7bee71ece0c8dfa1557aa2f45606/ctor/etc/nginx/sites-available/loglist#L50-L56

It's not enabled for any other sites.

**Comment by Minoru** [comment]
Thanks for the triage!

> Currently I'm thinking about dropping that www prefix at all. Any thoughts?

I think we can live without it, though I'd add it back when the certificate problem is resolved—someone might still have a www URL, and once it's set up it's easy to maintain.

> I don't think anybody has been using that redirect because of the certificate issues.

That redirect works over HTTP and redirects to non-www domain, so it doesn't trigger the certificate issue.

**Comment by ForNeVeR** [comment]
The issue has been resolved.
